Diagnostics:
  ClangTidy:
    Add:
      [
        "bugprone-*",
        "clang-analyzer-*",
        "concurrency-*",
        "cppcoreguidelines-*",
        "misc-*",
        "modernize-*",
        "performance-*",
        "portability-*",
        "readability-*",
      ]
    Remove:
      [
        "readability-identifier*",
        "readability-magic-numbers",
        "cppcoreguidelines-avoid-magic-numbers",
      ]
    CheckOptions:
      readability-implicit-bool-conversion.AllowPointerConditions: true

InlayHints:
  Enabled: Yes
